### ISSUE TITLE
Wrong magic number

### ISSUE THREAD

**Issue by joostflick** [peppequint/web-app-from-scratch-18-19#1]
https://github.com/peppequint/web-app-from-scratch-18-19/blob/df6041e69f431c338d32dd090b9f2a2879f0a20d/week1/public/js/app.js#L1

You're using a magic number which is a bad practice by itself, but it is also too high.
> **_Arrays start at 0 Peppe-Quint._**

I recommend using Array.prototype.length() to determine which random number to generate and prevent 404's.

**Comment by peppequint** [comment]
Done

**Comment by joostflick** [comment]
Niet

**Comment by peppequint** [comment]
deleted random number
